### ISSUE TITLE
칩 글자 줄바꿈되는 오류

### ISSUE THREAD

**Issue by reeactdev** [yooonspace/dimi-trending-repo-front#4]
환경: 크롬, 100%배율, innerwidth < 995일 때
![image](https://user-images.githubusercontent.com/35295182/72586977-f7679780-3936-11ea-9088-bcf32a999f0c.png)
위와 같이 디컨과, 웹플과 줄바꿈 됩니다
하하하하 고정 width로 해주세요
https://github.com/yooonspace/dimi-trending-repo-front/blob/master/src/components/ProfileBox.tsx#L31

**Comment by yooonspace** [comment]
로컬에선 잘 되는데요?

**Comment by yooonspace** [comment]
로컬에서도 안되네요. 수정하겠습니다.

**Comment by yooonspace** [comment]
개발자 프로필 UI 변경 예정으로 이슈는 닫겠습니다.
