### ISSUE TITLE
수정사항

### ISSUE THREAD

**Issue by yooonspace** [yooonspace/dimi-trending-repo-front#6]
- [x] dimigo.in auth
- [x] 프로필 ui 수정

**Comment by reeactdev** [comment]
개인프로필은 따로 창으로 할거에요? 아니면 팝업으로 할거에요?

**Comment by yooonspace** [comment]
@reeactdev 메인페이지 리스트 위에 띄울 예정이에욤

**Comment by yooonspace** [comment]
// 나중에 시간나면

개인 프로필 (페이지 or 메인 사이드) with localstorage
 다크모드 지원
